### ISSUE TITLE
Wire doesn't pass Akka.Serialization tests

### ISSUE THREAD

**Issue by alexvaluyskiy** [rogeralsing/Wire#22]
The latest Wire, which was built from sources (dotnetcore branch) doesn't pass Akka.Serialization tests, half of them failed:

``` C#
System.MissingMethodException

No parameterless constructor defined for this object.

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Wire.TypeExtensions.GetEmptyObject(Type type)
   at Wire.CodeGenerator.<>c__DisplayClass1_0.<MakeReader>b__0(Stream stream, DeserializerSession session)
   at Wire.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
   at Wire.Serializer.Deserialize[T](Stream stream)
   at Akka.Serialization.WireSerializer.FromBinary(Byte[] bytes, Type type) in C:\Projects\akka.net\src\contrib\serializers\Akka.Serialization.Wire\WireSerializer.cs:line 62
   at Akka.Tests.Serialization.AkkaSerializationSpec.AssertEqual[T](T message) in C:\Projects\akka.net\src\contrib\serializers\Akka.Serialization.TestKit\AkkaSerializationSpec.cs:line 276
   at Akka.Tests.Serialization.AkkaSerializationSpec.CanSerializeResizer() in C:\Projects\akka.net\src\contrib\serializers\Akka.Serialization.TestKit\AkkaSerializationSpec.cs:line 269
```

**Comment by rogeralsing** [comment]
The dotnet core branch was broken for some time, I'm fixing this now

**Comment by rogeralsing** [comment]
Fixed
