### ISSUE TITLE
Deserializing objects when a type is missing results in unexpected exception type

### ISSUE THREAD

**Issue by rogeralsing** [rogeralsing/Wire#9]
When deserializing a payload that reffers to a typename that is not present, there is:

arameter name: key] [ at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
at Wire.Serializer.GetCustomDeserialzer(Type type)
at Wire.Serializer.GetDeserializerByManifest(Stream stream, SerializerSession session)
at Wire.Serializer.DeserializeT
at Akka.Serialization.WireSerializer.FromBinary(Byte[] bytes, Type type)
at Akka.Remote.Serialization.MessageContainerSerializer.Deserialize(ByteString bytes, Type type, Int32 serializerId)

This needs to be handled with a better exception

**Comment by rogeralsing** [comment]
Same as #25
